include:
- ./func/*
kind: ArchiveUploadSpec
name: func-vnoK

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: watch-list-list-fn-906c4723-816d-4c59-bd4b-f9c927fd9d4d
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: watch-list-list-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-vnoK
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-31T18:46:54Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: watch-list-list-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: watch-list-list-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.list_symbols
    packageref:
      name: watch-list-list-fn-906c4723-816d-4c59-bd4b-f9c927fd9d4d
      namespace: default
  requestsPerPod: 100000
  resources: {}
